# Site settings
title: AkuPayu
description: 
baseurl: ""
url: "https://akupayu.vercel.app"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
